CompileFlags:
  Add:
    - -xc++
    - -std=c++17
    - --target=x86_64-w64-mingw32

    # For raylib and opengl lsp
    - -IC:/Users/Naman/Documents/libraries/raylib/raylib/src
    - -IC:/Users/Naman/Documents/libraries/glfw/glfw/include
